### ISSUE TITLE
UI is not being hiddden.

### ISSUE THREAD

**Issue by Slowmotion04** [PresNL/hide-widgets#12]
Gm gm!
I was recording yday using the plugin and it worked perfectly!
Today after a few hours seems that it's not working at all (yes I'm on resizable).

Any clues? Maybe it needs to be updated?

**Comment by joshperelmanhall** [comment]
Same issue. I found that on classic resizable it hides the midgets around the minimap (health, prayer, run energy) but not the minimap itself or any other UI elements.
