### ISSUE TITLE
Hide screen markers 

### ISSUE THREAD

**Issue by T7000** [PresNL/hide-widgets#3]
Yo, there's not much activity at [my feature request on the runelite github ](https://github.com/runelite/runelite/issues/10978) and I figured this might fit into your plugin.

**Comment by PresNL** [comment]
this falls under the feature requested here: https://github.com/PresNL/hide-widgets/issues/2 for now the workaround is simply to hide the runelite overlays yourself using their respective plugins. 

I also suspect this issue will remain open unless I can figure out a proper way of hiding all overlays from runelite which I don't think exists at the moment
