### ISSUE TITLE
Camera zoom

### ISSUE THREAD

**Issue by PaladinWat** [PresNL/hide-widgets#4]
Awesome plugin, very useful for screenshots, but hiding UI disables scrollwheel camera zoom. Any way to fix this?

**Comment by PresNL** [comment]
I don't have a dev environment set up atm to try and fix it but as a temporary work around using resizable modern layout seems to work (instead of resizeable classic layout)

**Comment by PresNL** [comment]
runelite/plugin-hub/pull/1862 this is now fixed with this pull request

**Comment by PaladinWat** [comment]
Really glad to hear about this fix! Thank you for the update!
